import { StandardTableView, LineEdit } from "std-widgets.slint";

component FileListView {
    VerticalLayout {
        spacing: 10px;
        LineEdit {
            text: "/usr/local/dingdong/foobar";
        }

        StandardTableView {
            columns: [
                { title: "Name", min-width: 100px },
                { title: "Size", min-width: 100px },
                { title: "Change Date", min-width: 100px },
            ];
            rows: [
                [{ text: "foo.txt" }, { text: "200KB" }, { text: "2025-07-17 10:30" }],
                [{ text: "bar.txt" }, { text: "200KB" }, { text: "2025-07-17 10:30" }],
            ];
        }

        LineEdit {
            placeholder-text: "glob-pattern";
        }
    }
}

export struct UISettings {
    fontsize: length,
    fontfamily: string,
}

export component AppWindow inherits Window {

    public function get_default_ui_settings() -> UISettings {
        return {
            fontsize: self.default-font-size,
            fontfamily: self.default-font-family,
        };
    }
    public function apply_ui_settings(settings: UISettings) {
        self.default-font-size = settings.fontsize;
        self.default-font-family = settings.fontfamily;
    }

    title: "Commander Fluffy";

    VerticalLayout {
        HorizontalLayout {
            padding: 10px;
            FileListView { }

            Rectangle {
                width: 10px;
            }

            FileListView { }
        }
    }
}
