import { StandardTableView, LineEdit } from "std-widgets.slint";

component FileListView {
    VerticalLayout {
        spacing: 10px;
        LineEdit {
            text: "/usr/local/dingdong/foobar";
        }

        StandardTableView {
            columns: [
                { title: "Name", min-width: 100px },
                { title: "Size", min-width: 100px },
                { title: "Change Date", min-width: 100px },
            ];
            rows: [
                [{ text: "foo.txt" }, { text: "200KB" }, { text: "2025-07-17 10:30" }],
                [{ text: "bar.txt" }, { text: "200KB" }, { text: "2025-07-17 10:30" }],
            ];
        }

        LineEdit {
            placeholder-text: "glob-pattern";
        }
    }
}

export component AppWindow inherits Window {

    public function set_font-size(parameter: length) {
        self.default-font-size = parameter;
    }

    public function set_font-family(name: string) {
        self.default-font-family = name;
    }

    title: "Commander Fluffy";

    VerticalLayout {
        HorizontalLayout {
            padding: 10px;
            FileListView { }

            Rectangle {
                width: 10px;
            }

            FileListView { }
        }
    }
}
